name: Build desktop apps

on:
  push:
    tags:
      - 'v*'   # run on version tags like v0.1.0
    branches: 
      - 'main'
  workflow_dispatch: {}

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_target: -l    # linux
          - os: windows-latest
            build_target: -w    # windows
          - os: macos-latest
            build_target: -m    # mac

    # defaults:
    #   run:
    #     working-directory: apps/electron   # <--- important for your structure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/electron/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build web SPA & deps
        run: npm exec turbo run build:electron -- --filter=@app/web

      - name: Build server
        run: npm run build
        working-directory: apps/server

      - name: Build electron app
        run: npm run build
        working-directory: apps/electron

      - name: Build distributables with electron-builder
        run: mkdir release/@app && npx electron-builder ${{ matrix.build_target }}
        working-directory: apps/electron

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}
          path: apps/electron/release/**
